apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:  # Correct field name: "template"
    metadata:
      labels:
        app: nginx
    spec:
      containers:  # Correct field name: "containers"
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80  # Correct field name: "containerPort"

